stages:
  - test
  - build
  - test2

test:
  stage: test
  image: golang:1.17
  script: 
   - go test .

build:
  stage: build
  image: docker:latest
  script:
   - docker build .

test2:
  stage: test2
  image: ubuntu:20.04
  script:
    - echo "Privet GitLab"
